<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            // BSCS Checklist
            // 1st sem (First Year)
            [
                'course_code' => 'GNED 02',
                'course_title' => 'Ethics',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'GNED 05',
                'course_title' => 'Purposive Communication',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'GNED 11',
                'course_title' => 'Kontesktwalisadong Komunikasyon sa Filipino',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'COSC 50',
                'course_title' => 'Discrete Structures I',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'DCIT 21',
                'course_title' => 'Introduction to Computing',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 6,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'DCIT 22',
                'course_title' => 'Computer Programming I',
                'credit_unit_lecture' => 1,
                'credit_unit_laboratory' => 2,
                'contact_hours_lecture' => 1,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'FITT 1',
                'course_title' => 'Movement Enhancement',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'NSTP 1',
                'course_title' => 'National Service Training Program 1',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'CvSU 101',
                'course_title' => 'Institutional Orientation',
                'credit_unit_lecture' => 1,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 1,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            // 2nd sem (First Year)
            [
                'course_code' => 'GNED 01',
                'course_title' => 'Art Appreciation',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            [
                'course_code' => 'GNED 03',
                'course_title' => 'Mathematics in the Modern World',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            [
                'course_code' => 'GNED 06',
                'course_title' => 'Science, Technology and Society',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],

            [
                'course_code' => 'GNED 12',
                'course_title' => 'Dalumat Ng/Sa Filipino',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "GNED 11",
            ],
            [
                'course_code' => 'DCIT 23',
                'course_title' => 'Computer Programming II',
                'credit_unit_lecture' => 1,
                'credit_unit_laboratory' => 2,
                'contact_hours_lecture' => 1,
                'contact_hours_laboratory' => 6,
                'pre_requisite' => "DCIT 22",
            ],

            [
                'course_code' => 'ITEC 50',
                'course_title' => 'Web Systems and Technologies',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 21",
            ],
            [
                'course_code' => 'FITT 2',
                'course_title' => 'Fitness Exercises',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "FITT 1",
            ],
            [
                'course_code' => 'NSTP 2',
                'course_title' => 'National Service Training Program 2',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "NSTP 1",
            ],

            // 1sd sem (2nd year) 
            [
                'course_code' => 'GNED 04',
                'course_title' => 'Mga babasahin Hinggil sa Kasaysayan ng Pilipinas',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            [
                'course_code' => 'MATH 1',
                'course_title' => 'Analytic Geometry',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "GNED 03",
            ],
            [
                'course_code' => 'COSC 55',
                'course_title' => 'Discrete Structures II',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "COSC 50",
            ],
            [
                'course_code' => 'COSC 60',
                'course_title' => 'Digital Logic Design',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "COSC 50, DCIT 23",
            ],
            [
                'course_code' => 'DCIT 50',
                'course_title' => 'Object Oriented Programming',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 23",
            ],
            [
                'course_code' => 'DCIT 24',
                'course_title' => 'Information Management',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 23",
            ],
            [
                'course_code' => 'INSY 50',
                'course_title' => 'Fundamentals of Information System',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "DCIT 21",
            ],
            [
                'course_code' => 'FITT 3',
                'course_title' => 'Physical Activity towards Health and Fitness 1',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "FITT 1",
            ],
            // IT checklist
            [
                'course_code' => 'ITEC 55',
                'course_title' => 'Platform Technologies',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 23",
            ],
            // 2nd sem (2nd year)
            [
                'course_code' => 'GNED 08',
                'course_title' => 'UnderStanding the self',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            [
                'course_code' => 'GNED 14',
                'course_title' => 'Panitikang Panlipunan',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            ['course_code' => 'MATH 2', 'course_title' => 'Calculus', 'credit_unit_lecture' => 3, 'credit_unit_laboratory' => 0, 'contact_hours_lecture' => 3, 'contact_hours_laboratory' => 0, 'pre_requisite' => "MATH 1",],
            [
                'course_code' => 'COSC 65',
                'course_title' => 'Architecture and Organization',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "COSC 60",
            ],
            [
                'course_code' => 'COSC 70',
                'course_title' => 'Software Engineering I',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "DCIT 50, DCIT 24",
            ],
            [
                'course_code' => 'DCIT 25',
                'course_title' => 'Data Structures and Algorithms',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 23",
            ],
            [
                'course_code' => 'DCIT 55',
                'course_title' => 'Advanced Database Management System',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 24",
            ],
            [
                'course_code' => 'FITT 4',
                'course_title' => 'Physical Activities towards Health and Fitness 2',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "FITT1",
            ],
            // IT checklist
            [
                'course_code' => 'ITEC 60',
                'course_title' => 'Integrated Programming and Technologies 1',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 50, ITEC 55",
            ],
            [
                'course_code' => 'ITEC 65',
                'course_title' => 'Open Source Technology',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "2nd year Standing",
            ],
            [
                'course_code' => 'ITEC 70',
                'course_title' => 'Multimedia Systems',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "2nd year Standing",
            ],

            // 1st sem (3rd year)
            [
                'course_code' => 'MATH 3',
                'course_title' => 'Linear Algebra',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "MATH 2",
            ],
            [
                'course_code' => 'COSC 75',
                'course_title' => 'Software Engineering II',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "COSC 70",
            ],
            [
                'course_code' => 'COSC 80',
                'course_title' => 'Operating Systems',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 25",
            ],
            [
                'course_code' => 'COSC 85',
                'course_title' => 'Networks and Communication',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 50",
            ],
            [
                'course_code' => 'COSC 101',
                'course_title' => 'CS Elective 1 (Computer Graphics and Visual Computing)',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "DCIT 23",
            ],
            [
                'course_code' => 'DCIT 26',
                'course_title' => 'Application Dev\'t and Emerging Technologies',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 50",
            ],
            [
                'course_code' => 'DCIT 65',
                'course_title' => 'Social and Professional Issues',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            //IT Checklist
            [
                'course_code' => 'ITEC 90',
                'course_title' => 'Network Fundamentals',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 55",
            ],
            [
                'course_code' => 'INSY 55',
                'course_title' => 'System Analysis and Design',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "3rd year Standing",
            ],
            // 2nd sem (3rd year)
            [
                'course_code' => 'GNED 09',
                'course_title' => 'Life and Works of Rizal',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "GNED 04",
            ],
            [
                'course_code' => 'MATH 4',
                'course_title' => 'Experimental Statistics',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "MATH 2",
            ],
            [
                'course_code' => 'COSC 90',
                'course_title' => 'Design and Analysis',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "DCIT 25",
            ],
            [
                'course_code' => 'COSC 95',
                'course_title' => 'Programming Languages',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "DCIT 25",
            ],
            [
                'course_code' => 'COSC 106',
                'course_title' => 'CS Elective (Introduction to Game Development)',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "MATH 3, COSC 101",
            ],
            [
                'course_code' => 'DCIT 60',
                'course_title' => 'Methods of Research',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "3rd year Standing",
            ],
            [
                'course_code' => 'ITEC 85',
                'course_title' => 'Information Assurance and Security',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "DCIT 24",
            ],
            // IT checklist
            [
                'course_code' => 'ITEC 95',
                'course_title' => 'Quantitative Methods (Modeling & Simulation)',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "COSC 50, STAT 2",
            ],
            [
                'course_code' => 'ITEC 101',
                'course_title' => 'IT ELECTIVE 1 (Human Computer Interaction 2)',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 80",
            ],
            [
                'course_code' => 'ITEC 106',
                'course_title' => 'IT ELECTIVE 2 (Web System and Technologies 2)',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 50",
            ],
            [
                'course_code' => 'ITEC 100',
                'course_title' => 'Information Assurance and Security 2',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 85",
            ],
            [
                'course_code' => 'ITEC 105',
                'course_title' => 'Network Management',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 90",
            ],
            [
                'course_code' => 'ITEC 200A',
                'course_title' => 'Capstone Project and Research 1',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "DCIT 60, DCIT 26, ITEC 85, 70% total units taken",
            ],

            // midyear
            [
                'course_code' => 'COSC 199',
                'course_title' => 'Practicum (240 hours)',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 0,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "incoming 4th year",
            ],
            // midyear IT
            [
                'course_code' => 'STAT 2',
                'course_title' => 'Applied Statistics',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "2nd year Standing",
            ],
            [
                'course_code' => 'ITEC 75',
                'course_title' => 'System Integration and Architecture 1',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 60",
            ],

            // 1st sem (4th year)
            [
                'course_code' => 'ITEC 80',
                'course_title' => 'Human Computer Interaction',
                'credit_unit_lecture' => 1,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "ITEC 85",
            ],
            [
                'course_code' => 'COSC 100',
                'course_title' => 'Automata Theory and Formal Language',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "COSC 90",
            ],
            [
                'course_code' => 'COSC 105',
                'course_title' => 'Intelligent System',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "MATH 4, COSC 55, DCIT 50",
            ],
            [
                'course_code' => 'COSC 111',
                'course_title' => 'CS Elective 3 (Internet of Things)',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "COSC 60",
            ],
            [
                'course_code' => 'COSC 200A',
                'course_title' => 'Undergraduate Thesis I',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 1,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "4th year Standing",
            ],
            // IT Checklist
            [
                'course_code' => 'ITEC 111',
                'course_title' => 'IT ELECTIVE 3 (Integrated Programming and Technologies 2)',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 60",
            ],
            [
                'course_code' => 'ITEC 116',
                'course_title' => 'IT ELECTIVE 4 (Systems Integration and Architecture 2)',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 75",
            ],
            [
                'course_code' => 'ITEC 110',
                'course_title' => 'Systems Administration and Maintenance',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "ITEC 100",
            ],
            [
                'course_code' => 'ITEC 200B',
                'course_title' => 'Capstone Project and Research 2',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "ITEC 200A",
            ],
            // 2nd sem (4th year)
            [
                'course_code' => 'GNED 07',
                'course_title' => 'The Contemporary World',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            [
                'course_code' => 'GNED 10',
                'course_title' => 'Gender and Society',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 3,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => null,
            ],
            [
                'course_code' => 'COSC 110',
                'course_title' => 'Numerical and Symbolic Computation',
                'credit_unit_lecture' => 2,
                'credit_unit_laboratory' => 1,
                'contact_hours_lecture' => 2,
                'contact_hours_laboratory' => 3,
                'pre_requisite' => "COSC 60",
            ],
            [
                'course_code' => 'COSC 200B',
                'course_title' => 'Undergraduate Thesis II',
                'credit_unit_lecture' => 3,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 1,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "COSC 200A",
            ],
            //IT Checlist
            [
                'course_code' => 'ITEC 199',
                'course_title' => 'Practicum (minimum 486 hours)',
                'credit_unit_lecture' => 6,
                'credit_unit_laboratory' => 0,
                'contact_hours_lecture' => 0,
                'contact_hours_laboratory' => 0,
                'pre_requisite' => "DCIT 26, ITEC 85, 70% total units taken",
            ],
        ];

        DB::table('courses')->insert($courses);
    }
}
